sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/centralized-webphone-base
  - secure: IGaMDMO3/vqiGMClPP/PDa3QKgnJ86OwmwqPChNPmJvo9wYftSljijgJqLWbt/JBApjTdI02gaXq/Jyj9VrO2hSyxWngTvYb40P36w1t+CcXOtNhFZ6SbERuwBh8AgPp3dTRu+0Y2IQUkkgPlJpFj7d7KnQHCAI1/jWvcA+5Psku5w5vqiWqCwZqAVJTF5JozEuVfFZff0YPfecIvcQxmp1ay48dYwBrR+F8Iyw9O73xQkFoFCc5HfhW9KMroAyuYOZjk9Q6pBVKmvC15/S4dPx0CYf7XorJLDOt2Gx1EreC/4zTkwXNiFbYmAv6Bp/b+NtIzzJs2Ev5VNeR1lrD00HtZ72LUi3d1Nx0/nrVGMAM0/nUlJsmGBetoH1A046dK+bfxwqPR+75/KI0URcyELmVVL3nifEcdP6yp1l8JC/IFOxIzOwBNKnK4EnW6rZHunY/J+FJeHcU/an4rMS1zuVX07DT7mEFx76LTWI7SnnnAdO6wUphgcBoL/is/IdhAq1yW/3rbPJ/RSyamXKD8Zvfd6AYXKRfSXL4GfXh/uugjzfSX8qX4LpfPQY8PhkMTgkRO0IWbwnNX16DRX/ReA6U9D5fUnp4cC83tWwsfRyiWYaLaqpLHWzEmQP0sSSHrcBh+0T7qfb4MMgL48b+dgjYMn9jrAKbhzIHcJT4Esg=
  - secure: ejDcs/PKvq2BdFZ1djeToFAGoZLy5tlOTyFzO4mGNdmbDPnogc41tXR852P3ZTiOCtRA7mcmgRDskK5Vt0h+wjF2CU9o13skyQ6TE/UjbxrEFQ5eTb6/P7F/FuVYqijgqjg+CAB6UyqIYwieFSx8K9qeisCrEiB7HzPerytkZ+BMg137aRBI7+qiR71tlHCbrtbavcvuuiH3WJ4S3nHxuW7CcTt+dOPctJs+ISONM4U7Rw0frrtmKVJhZnuxcj0b3kxN4eQ1FYVwThQAZdeJbylhWu1l2Ekrt0m5B4gdurVuOR0qDYxmuSuxIIFhHxVebNIPNuNHO9FlPPk9QPTTzG7sGh7ymvLRSWapTSxyqi8hpXqwxusgETg9uG6Q1yBxpnAJYqsnG3K84U0aN4D0iQU5A4D27oMAJEPfkdZiTE7lVukshF9oY+XeAIYLE6HWsc0iOu+lqRdjsdUa5isMbKjH5P39kTU6DJCxOtcnE40vh/zYUCNDefox3xls9ryj4wCajko5pvxrjC2KGCpiTBgCy8UkSsfuN0gb4+9cW3qtKttIPizKdYGxABCI8BHYo2jP0hT/Srel/OGb0XiXrcOXUlu8RsLLl1rh+ZL7TZoUfQoGLm0DtPsJ3FDxSOTFi9pGsElEoqmK5x2I5ShFkhk/nuO48tyOXDqUIlQRvfk=
before_script:
- node_version="$(awk -F '[:-]' '/FROM/ {print $2}' Dockerfile)"
- pjsip_version="$(awk '/ENV VERSION_PJSIP/ {print $3}' Dockerfile)"
- chromium_version="$(awk '/ENV VERSION_CHROMIUM/ {print $3}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:node${node_version}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:node${node_version}-pjsip${pjsip_version}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:node${node_version}-pjsip${pjsip_version}-chromium${chromium_version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:node${node_version}" && docker push "${IMAGE_NAME}:node${node_version}-pjsip${pjsip_version}" && docker push "${IMAGE_NAME}:node${node_version}-pjsip${pjsip_version}-chromium${chromium_version}"
  on:
    branch: master
